env: "local"
log_path_agent: "./backend/agent.log"
log_path_orchestrator: "./backend/orchestrator.log"
inactive_time_for_agent: 200
time_for_ping: 100
rabbit_queue:
  rabbitmq_url: "amqp://guest:guest@localhost:5672/"
  queue_for_expressions_to_agents: "Expressions to agents"
  queue_for_results_from_agents: "Results from agents"
http_server:
  address: "localhost:3000"
  timeout: 4s
  idle_timeout: 60s
database_instance:
  goose_migration_dir: "./backend/sql/schema"
  storage_url: "postgres://postgres:6,62607004@localhost:5434/daee?sslmode=disable"