env: "local"
rabbit_queue:
  rabbitmq_url: "amqp://guest:guest@localhost:5672/"
  queue_for_send_to_agents: "Expressions to agents"
  queue_for_consume_from_agents: "Results from agents"
http_server:
  address: "localhost:3000"
  timeout: 4s
  idle_timeout: 60s
database_instance:
  goose_migration_dir: "./backend/sql/schema"
  storage_url: "postgres://postgres:6,62607004@localhost:5434/daee?sslmode=disable"