// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: expressions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExpression = `-- name: CreateExpression :one
INSERT INTO expressions (id, created_at, updated_at, data, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, data, status
`

type CreateExpressionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Data      string
	Status    string
}

func (q *Queries) CreateExpression(ctx context.Context, arg CreateExpressionParams) (Expression, error) {
	row := q.db.QueryRowContext(ctx, createExpression,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Data,
		arg.Status,
	)
	var i Expression
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Data,
		&i.Status,
	)
	return i, err
}
