// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: expressions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExpression = `-- name: CreateExpression :one
INSERT INTO expressions (id, created_at, updated_at, data, parse_data, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, data, status, parse_data
`

type CreateExpressionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Data      string
	ParseData string
	Status    string
}

func (q *Queries) CreateExpression(ctx context.Context, arg CreateExpressionParams) (Expression, error) {
	row := q.db.QueryRowContext(ctx, createExpression,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Data,
		arg.ParseData,
		arg.Status,
	)
	var i Expression
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Data,
		&i.Status,
		&i.ParseData,
	)
	return i, err
}

const getExpressionByID = `-- name: GetExpressionByID :one
SELECT id, created_at, updated_at, data, status, parse_data FROM expressions
WHERE id = $1
`

func (q *Queries) GetExpressionByID(ctx context.Context, id uuid.UUID) (Expression, error) {
	row := q.db.QueryRowContext(ctx, getExpressionByID, id)
	var i Expression
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Data,
		&i.Status,
		&i.ParseData,
	)
	return i, err
}

const getExpressions = `-- name: GetExpressions :many
SELECT id, created_at, updated_at, data, status, parse_data FROM expressions
`

func (q *Queries) GetExpressions(ctx context.Context) ([]Expression, error) {
	rows, err := q.db.QueryContext(ctx, getExpressions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expression
	for rows.Next() {
		var i Expression
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Data,
			&i.Status,
			&i.ParseData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
