// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Expression struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Data      string
	Status    string
	ParseData string
}
