// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: operations.sql

package postgres

import (
	"context"
)

const createOperation = `-- name: CreateOperation :exec
INSERT INTO operations (operation_type, execution_time)
VALUES ($1, $2)
RETURNING
    operation_id, operation_type, execution_time
`

type CreateOperationParams struct {
	OperationType string
	ExecutionTime int32
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) error {
	_, err := q.db.ExecContext(ctx, createOperation, arg.OperationType, arg.ExecutionTime)
	return err
}

const getOperationByType = `-- name: GetOperationByType :one
SELECT
    operation_id, operation_type, execution_time
FROM operations
WHERE operation_type = $1
`

func (q *Queries) GetOperationByType(ctx context.Context, operationType string) (Operation, error) {
	row := q.db.QueryRowContext(ctx, getOperationByType, operationType)
	var i Operation
	err := row.Scan(&i.OperationID, &i.OperationType, &i.ExecutionTime)
	return i, err
}

const getOperationTimeByType = `-- name: GetOperationTimeByType :one
SELECT execution_time FROM operations
WHERE operation_type = $1
`

func (q *Queries) GetOperationTimeByType(ctx context.Context, operationType string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOperationTimeByType, operationType)
	var execution_time int32
	err := row.Scan(&execution_time)
	return execution_time, err
}

const getOperations = `-- name: GetOperations :many
SELECT
    operation_id, operation_type, execution_time
FROM operations
ORDER BY operation_type DESC
`

func (q *Queries) GetOperations(ctx context.Context) ([]Operation, error) {
	rows, err := q.db.QueryContext(ctx, getOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(&i.OperationID, &i.OperationType, &i.ExecutionTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperationTime = `-- name: UpdateOperationTime :one
UPDATE operations
SET execution_time = $1
WHERE operation_type = $2
RETURNING operation_id, operation_type, execution_time
`

type UpdateOperationTimeParams struct {
	ExecutionTime int32
	OperationType string
}

func (q *Queries) UpdateOperationTime(ctx context.Context, arg UpdateOperationTimeParams) (Operation, error) {
	row := q.db.QueryRowContext(ctx, updateOperationTime, arg.ExecutionTime, arg.OperationType)
	var i Operation
	err := row.Scan(&i.OperationID, &i.OperationType, &i.ExecutionTime)
	return i, err
}
