name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          cache: false

      - name: Install dependencies
        run: go mod download

      - name: Run golangci-lint
        run: |
          cd backend
          /home/runner/golangci-lint-1.54.2-linux-amd64/golangci-lint run --out-format=github-actions
